# Generated by Django 2.1.8 on 2020-06-25 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesave',
            name='input_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='timesave',
            name='save_date',
            field=models.IntegerField(default=0),
        ),
    ]
