# Generated by Django 2.1.8 on 2020-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0003_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='n_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
