# Generated by Django 2.1.8 on 2020-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesave',
            name='input_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
