# Generated by Django 2.1.8 on 2020-07-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0007_auto_20200728_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesave',
            name='input_date',
        ),
        migrations.AddField(
            model_name='timesave',
            name='input_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timesave',
            name='input_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timesave',
            name='input_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
