# Generated by Django 2.1.8 on 2020-07-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0008_auto_20200729_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesave',
            old_name='input_day',
            new_name='input_date',
        ),
        migrations.RemoveField(
            model_name='timesave',
            name='input_month',
        ),
        migrations.RemoveField(
            model_name='timesave',
            name='input_year',
        ),
    ]
