# Generated by Django 2.1.8 on 2020-07-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeUser', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
