# Generated by Django 2.1.8 on 2020-07-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeUser', '0003_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
