# Generated by Django 2.1.8 on 2020-07-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeUser', '0005_auto_20200704_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
